name 'apache'
depends 'mysql'
depends 'apparmor'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures vim_pruebas_chef'
long_description 'Installs/Configures vim_pruebas_chef'
version '0.1.0'
chef_version '>= 14.0'